### PR TITLE
Fix some bugs in recursiveVectors.

### PR DESCRIPTION
**Pull request by ketch**
Also use "plt" instead of "pl" for matplotlib.

### CODE REVIEW

**Comment by ketch** [comment]
@mikaem Could you explain?  Matplotlib has been a required dependency (in requirements.txt) for a long time.

**Comment by mikaem** [comment]
Well, it has never actually been required before, when importing nodepy. But now, see https://circleci.com/gh/spectralDNS/spectralDNS/283?utm_campaign=build-failed&utm_medium=email&utm_source=notification

**Comment by ketch** [comment]
Now I'm really confused.  In that log I see

    Running setup.py install for nodepy ... - \ | done

And the setup.py file includes the line

    install_requires=['numpy','sympy','matplotlib','networkx']

So how is matplotlib not installed?

**Comment by mikaem** [comment]
I'm installing nodepy using 'pip install --no-deps git+https://github.com/ketch/nodepy.git@master'
So, no deps.

**Comment by ketch** [comment]
When I started programming in Python, I imported things wherever I needed them.  Then somebody taught me about PEP8 and I started moving all my imports to the top of the file.  Sometimes this ends up seeming like a bad idea.

Of course, it should be pointed out that many things within nodepy will not work for you (I know that this is acceptable in your case).  The fact is that I never imagined somebody using nodepy in the way you do when I wrote it.

I don't mind putting those imports back inside functions for now, though.

**Comment by mikaem** [comment]
Great thanks:-) For the record, if you think otherwise and decide to really make matplotlib a required dependency (i.e., required for import nodepy), then you should do that and it's really no problem for me to modify. I'm currently only using nodepy for some BS5 parameters in an integrator that Nathanael implemented.

**Comment by ketch** [comment]
Yeah, it would probably make sense for you to just put those coefficients in a file somewhere and not depend on nodepy.  But if somebody wants to explore other integrators this link could be helpful.

**Pull request merged**
