### PR TITLE
Change return type in RK 

### PR DESCRIPTION
**Pull request by mikaem**
With current `np.zeros((size))`(see diff) it is not possible to use complex numbers on the right hand side, and it is not possible to use multidimensional data. With this modification I can use nodepy to integrate as seen here:

https://github.com/spectralDNS/shenfun/blob/master/demo/KleinGordon_nodepy.py

More specifically, I'm using a nodepy integrator to solve the problem discretized otherwise as described here: https://rawgit.com/spectralDNS/shenfun/master/docs/src/KleinGordon/kleingordon_bootstrap.html

The if-else is required because u can be either np.array or a float. Couldn't think of a better way.

I would also suggest that `y` and `fy` are created once, on the first step, and then reused on later steps. But I've not done anything regarding that here.

### CODE REVIEW

**Comment by mikaem** [comment]
Any comments @ketch ? I have no idea why codecov complains about graph.py when there is no change in that file. But I could alternatively create a new clean fork and try again?

**Comment by ketch** [comment]
This is nice; thanks!  Please note that nodepy was specifically NOT designed for performance so I don't encourage using it for this type of thing.  Obviously it is quite wasteful to allocate these arrays every time inside `__step__`, for instance.

We don't need to worry about codecov; I think it is buggy.  But it might be nice to replace the if-statements with a use of `numpy.asarray`; see https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.asarray.html.  My understanding is that the performance should not be worse, and I think the code will look neater.

**Comment by mikaem** [comment]
I understand that performance is not a major concern, and I suppose the major difficulty in that regard is with the Butcher or Shu-Osher coefficients that necessarily contains lots of redundant zeros when implemented generically. But it takes very little coding effort to preallocate and vectorize, trying to avoid generation of new arrays. Just good numpy coding practise:-) 
I'm not very concerned with performance here though, just looking for an integrator to easily apply to a range of spectral Galerkin problems using the `shenfun` package. For demonstration purposes.

More to the point of this PR, with `asarray` on a scalar the outcome is an array without length or shape that cannot be indexed, so it won't work without some further modifications. 

    In [12]: u = 1.0
    In [13]: np.asarray(u)
    Out[13]: array(1.0)
    In [14]: np.asarray(u).shape
    Out[14]: ()

However, I did come across another function `np.atleast_1d` that does the trick:-)

I also updated networkx to be at >=2.0, since this is the new release you get from pip or conda-forge and it requires 3-4 changes in `nodepy/graph.py`.

**Comment by ketch** [comment]
Thanks!  This looks good.

**Pull request merged**
