### PR TITLE
TSRK example 

### PR DESCRIPTION
**Pull request by sconde**
I've had this for a while now. I wasn't quite sure if you wanted an example like this. Is this ok?

### CODE REVIEW

**Comment by ketch** [comment]
This is very nice.  What I would like to have is the coefficients of some TSRK methods added to the file `twostep_runge_kutta_method.py`, so that one can do something like

    from nodepy import twostep_runge_kutta_method as tsrk
    my_tsrk = tsrk.load_method('name of some method')

similar to what is available in `rk.loadRKM()`.

The next step would be to add a method `__step__` to the TSRK class, which would contain some of the code from your example.

**Comment by ketch** [comment]
Also, you don't need to reference the issue tracker in the code that you commit -- that kind of thing should go in your commit message instead.

**Comment by sconde** [comment]
@ketch why do you use a list for u, t, dthist,etc. in ode_solver.py? Why not a numpy.array?

**Comment by ketch** [comment]
>why do you use a list for u, t, dthist,etc. in ode_solver.py? Why not a numpy.array?

>with numpy array, I'm able to pass in the old step without modifying the step definition. Also, isn't appending to a list not efficient in terms of memory?

You're right that those routines have not been written with efficiency in mind.  A numpy array might work better, but the first issue that comes to mind is that you would need to know the size of the array in advance, which you generally don't (since the timestepping can be adaptive).  But if you see a good way to implement this with a numpy array, and it turns out to be cleaner or faster, please do send me a PR.

**Pull request closed without merging**
